name: MineralLimiter
version: 0.0.1
description: Yet another useless Minecraft Craftbukkit plugin.
author: Saren
website: https://github.com/Saren-Arterius/MineralLimiter
 
main: net.wtako.MineralLimiter.Main
database: true

commands:
    mlimit:
        description: Basic command.
        usage: Type /<command> help to get help.
        permission: MineralLimiter.admin
        permission-message: You are not permitted to use this plugin.

permissions:
    MineralLimiter.*:
        description: Gives access to all MineralLimiter commands.
        default: op
    MineralLimiter.admin:
        description: Gives access to all MineralLimiter administrative commands.
        children:
            MineralLimiter.disableOnPlayer: true
            MineralLimiter.reload: true
        default: op
    MineralLimiter.disableOnPlayer:
        description: Players with this permission will not be affected by this plugin.
        default: op
    MineralLimiter.reload:
        description: Reloads the plugin.
        default: op