variable:
    ReverseAffectedWorlds: No
    AffectedWorlds:
    - world
    - world_nether
    AffectedBlockTypes:
    - DIAMOND_ORE
    - EMERALD_ORE
    - GOLD_ORE
    - IRON_ORE
    - LAPIS_ORE
    - REDSTONE_ORE
    - COAL_ORE
    TimeLimit: 86400
    BlockTypesLimitPerPeriod:
        # Set value to 0 to disable allowance
        Default: 16
        DIAMOND_ORE: 3
        EMERALD_ORE: 3
        GOLD_ORE: 5
        IRON_ORE: 10
        COAL_ORE: 32
    NoDropsIfOverLimit: Yes
    # Overrides NoDropsIfOverLimit
    CancelEventIfOverLimit: No
    IgnoreCreative: Yes
    
system:
    PluginVersion: ${version}